# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56446157810bc0e2857b281685e8790aee4c1e58506e5c2d54ecb0b1f6db1686366a4ac7c3ebf018c5e748038079f363dd93beae9437d0cdd6e51f9c12781981

test:
  secret_key_base: 690946faebe8d121b08b219e683e3e47d34983edf487314563b15e4d6ab0722e511ab722fa798810aac4c2afe1af86584b9eb23e8811f16ce0b4abc01729a373

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
